version: '3.7'
services:
     tripshare_db:
         image: postgres:13.3
         environment:
             - POSTGRES_USER=postgres
             - POSTGRES_PASSWORD=postgres
         ports:
             - '5432:5432'
         volumes:
             - ./db/db_setup/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
     tripshare_api:
         build: './api/'
         ports:
             - '3000:3000'
         depends_on:
             - tripshare_db
            #  - redis
    #  streamingwars_ui:
    #      build: './ui/'
    #      ports:
    #          - '80:80'
    #      depends_on:
    #          - streamingwars_api
    #  redis:
    #      image: "redis:alpine"
    #      ports:
    #          - '6379:6379'
             
